### PR TITLE
Fixing centering the sections

### PR DESCRIPTION
**Pull request by javpet**
– Fixed centering the sections
- Tried to solve some of the image stretching issues but couldn't really test

Fixes some of #18

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @javpet - can you not test on https://www.browserling.com/ ?

**Comment by tansaku** [comment]
I'm just looking at the netlify preview build in https://www.browserling.com/browse/win/7/ie/11/https%3A%2F%2Fdeploy-preview-41--folk-on-the-hill.netlify.com%2F

**Comment by javpet** [comment]
I could but you have a 3 mins limitations :/

**Comment by tansaku** [comment]
centering looks better than before - great work  - btw would it make sense to use something like bootstrap or semantic to get older browser support for free out of the box?  Or is that a lot more work and/or style inhibiting?

**Comment by javpet** [comment]
It would be actually bigger mess sadly :/

**Comment by tansaku** [comment]
Okay so browserstack a priority then ...

**Pull request merged**
